<?php

namespace ClubSpeed\Database\Records;

class Customers extends BaseRecord {
    protected static $_definition;

    public $CustID;
    public $Company;
    public $FName;
    public $LName;
    public $RacerName;
    public $BirthDate;
    public $IgnoreDOB;
    public $Gender;
    public $EmailAddress;
    public $SourceID;
    public $Hotel;
    public $IndustryID;
    public $RefID;
    public $DoNotMail;
    public $Address;
    public $Address2;
    public $City;
    public $State;
    public $Zip;
    public $Country;
    public $PhoneNumber;
    public $PhoneNumber2;
    public $Cell;
    public $Fax;
    public $LicenseNumber;
    public $IssuedBy;
    public $Waiver;
    public $Waiver2;
    public $CrdID;
    public $RPM;
    public $AccountCreated;
    public $LastVisited;
    public $TotalVisits;
    public $TotalRaces;
    public $MembershipStatus;
    public $MembershipText;
    public $MemberShipTextLong;
    public $PriceLevel;
    public $PromotionCode;
    public $IsGiftCard;
    public $WebUserName;
    // public $Password;
    public $Award1;
    public $Award2;
    public $Custom1;
    public $Custom2;
    public $Custom3;
    public $Custom4;
    public $Privacy1;
    public $Privacy2;
    public $Privacy3;
    public $Privacy4;
    public $Status1;
    public $Status2;
    public $Status3;
    public $Status4;
    public $Deleted;
    public $IsEmployee;
    public $OriginalID;
    public $CreditLimit;
    public $CreditOnHold;
    // public $LastUnSubscribedDate;
    public $GeneralNotes;
    public $Hash;
}