<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Twig_' => array($vendorDir . '/twig/twig/lib'),
    'Symfony\\Component\\Yaml\\' => array($vendorDir . '/symfony/yaml'),
    'Symfony\\Component\\HttpFoundation\\' => array($vendorDir . '/symfony/http-foundation'),
    'Symfony\\Component\\EventDispatcher\\' => array($vendorDir . '/symfony/event-dispatcher'),
    'Omnipay\\Tests\\' => array($vendorDir . '/omnipay/tests/src'),
    'Omnipay\\Mollie\\' => array($vendorDir . '/omnipay/mollie/src'),
    'Omnipay\\Common\\' => array($vendorDir . '/omnipay/common/src'),
    'Omnipay\\Buckaroo\\' => array($vendorDir . '/omnipay/buckaroo/src'),
    'Omnipay\\iDEAL\\' => array($vendorDir . '/omnipay/ideal/src'),
    'Omnipay\\Rabobank\\' => array($vendorDir . '/omnipay/rabobank/src'),
    'Omnipay\\WorldPayXML\\' => array($vendorDir . '/omnipay/worldpayxml/src'),
    'Mockery' => array($vendorDir . '/mockery/mockery/library'),
    'Guzzle\\Stream' => array($vendorDir . '/guzzle/stream'),
    'Guzzle\\Plugin\\Mock' => array($vendorDir . '/guzzle/plugin-mock'),
    'Guzzle\\Plugin\\Cookie' => array($vendorDir . '/guzzle/plugin-cookie'),
    'Guzzle\\Parser' => array($vendorDir . '/guzzle/parser'),
    'Guzzle\\Http' => array($vendorDir . '/guzzle/http'),
    'Guzzle\\Common' => array($vendorDir . '/guzzle/common'),
    'ClubSpeed' => array($baseDir), // note -- this was patched in by hand, and our structure doesn't quite match typical autoload folders -- might want to bury ./ClubSpeed under ./clubspeed/ClubSpeed
);
