<?php
/**
 * Club Speed API
 * 
 * Proposed API for accessing racer, heat and scoring information
 * generated by Club Speed server.
 * @author Wes Ratcliff <wes@clubspeed.com>
 * @version 0.1
 */
class Karting
{
    public $restler;
    
	function __construct(){
		header('Access-Control-Allow-Origin: *'); //Here for all /say
	}

	
	public function index() {
		// API Docs I Like: http://openbeerdatabase.com/
		// http://hurl.it/
		$daily_key = SimpleAuth::daily_key();
		$html = <<<EOH
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Events and Karting API - Club Speed</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Club Speed API">
    <meta name="author" content="Club Speed Timing">
	
    <!-- Le styles -->
    <link href="css/bootstrap.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet" media="print">
    <link href="css/myresume.css" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="img/favicon.ico">
  </head>

  <body>
  
    <div class="container">
      <div class="row">		
        <div class="span8">
          <div class="hero-unit">
            <p>Welcome to the Club Speed API. If you come up with a cool use of this data, <a href="mailto:support@clubspeed.com">drop me a line</a> and brag about it!</p>
            <p><em>Disclaimer: This is a BETA API, methods and parameters subject to change without notice</em></p>
		  </div>
		  
		  <div class="header">
			<h2>Getting Started.</h2>
			<hr />
		  </div>
		  
          <div class="row">
                    <div class="span8">
                        <div class="wannabe-unit">
                        <p>We currently have our Rental Karting data exposed and documented below.</p>
                    </div>
                </div><!--/span-->
          </div>
          
          <div class="row-fluid">
            <div class="span6">
              <h4><i class="icon-plus"></i> Caching</h4>
              <p>Currently, no requests are cached. </p>
            </div><!--/span-->
            <div class="span6">
              <h4><i class="icon-plus"></i> Rate Limiting</h4>
              <p>The API is not currently rate limited. Please use good judgment when designing your application.</p>
            </div><!--/span-->
          </div><!--/row-->
		  <div class="row-fluid">
            <div class="span6">
              <h4><i class="icon-plus"></i> Output Formats</h4>
              <p>We currently support JSON, JSONP &amp; XML (plus iCal on Events).</p>
            </div><!--/span-->
            <div class="span6">
              <h4><i class="icon-plus"></i> Questions/Requests</h4>
              <p><a href="mailto:support@clubspeed.com">Email us</a> with any API questions or requests.</p>
            </div><!--/span-->
          </div><!--/row-->
		  

		  <div class="header">
			<h2>Rental Karting.</h2>
			<hr />
		  </div>
          
          <div class="row">
            <div class="span8">
                <div class="wannabe-unit">
                <p>Use these methods to retrieve rental karting data.</p>
                    <p>You will need a key to access the Karting API or you may use our daily "testing" key below. Email <a href="mailto:support@clubspeedtiming.com">me</a> to obtain your own.</p>
    <p>Today's testing key is: <strong>{$daily_key}</strong></p>
                </div>
            </div><!--/span-->
            <div class="span8">
                    <h4><i class="icon-plus"></i> Racers</h4>
                    <p class="description">
                        Use these methods to find a racer's "racer_id" which can be used to get information on both the racer and the races they have participated in. Without a field parameter this is a wildcard match across First Name, Last Name, Racer Name and Email. It is possible to specify a specific field. "field=email" is currently supported. See email example below for usage.<br/>
                    </p>
                    <ul>
                        <li><strong>Find racer_id by Nickname:</strong> <code>/racers/search?query=Wes Ratcliff</code> (<a href="index.php/racers/search.json?query=Wes%20Ratcliff&key=$daily_key">JSON</a>, <a href="index.php/racers/search.js?query=Wes%20Ratcliff&key=$daily_key&callback=myCallback">JSONP</a>, <a href="index.php/racers/search.xml?query=Wes%20Ratcliff&key=$daily_key">XML</a>)</li>
                        <li><strong>Find racer_id by Email:</strong> <code>/racers/search?field=email&amp;query=wes@nolamotor.com</code> (<a href="index.php/racers/search.json?field=email&amp;query=wes@nolamotor.com&key=$daily_key">JSON</a>, <a href="index.php/racers/search.js?field=email&amp;query=wes@nolamotor.com&key=$daily_key&callback=myCallback">JSONP</a>, <a href="index.php/racers/search.xml?field=email&amp;query=wes@nolamotor.com&key=$daily_key">XML</a>)</li>
                        <li><strong>Find Racer by racer_id:</strong> <code>/racers/1000002</code> (<a href="index.php/racers/1000002.json?key=$daily_key">JSON</a>, <a href="index.php/racers/1000002.js?key=$daily_key&callback=myCallback">JSONP</a>, <a href="index.php/racers.xml/1000002?key=$daily_key">XML</a>)</li>
                        <li><strong>Find Racer's Races:</strong> <code>/racers/1000002/races</code> (<a href="index.php/racers/1000002/races.json?key=$daily_key">JSON</a>, <a href="index.php/racers/1000002/races.js?key=$daily_key&callback=myCallback">JSONP</a>, <a href="index.php/racers.xml/1000002/races?key=$daily_key">XML</a>)</li>
                        <li><strong>Top RPM Ranking</strong>
                            <ul>
                                <li><strong>Limt:</strong> <code>/racers/toprpm?limit=5</code> (<a href="index.php/racers/toprpm.json?limit=5&key=$daily_key">JSON</a>, <a href="index.php/racers/toprpm.js?limit=5&key=$daily_key&callback=myCallback">JSONP</a>, <a href="index.php/racers/toprpm.xml?limit=5&key=$daily_key">XML</a>)</code></li>
                                <li><strong>Gender (m: Male, f: Female):</strong> <code>/racers/toprpm?gender=m</code> (<a href="index.php/racers/toprpm.json?gender=f&key=$daily_key">JSON</a>, <a href="index.php/racers/toprpm.js?gender=f&key=$daily_key&callback=myCallback">JSONP</a>, <a href="index.php/racers/toprpm.xml?gender=f&key=$daily_key">XML</a>)</code></li>
                                <li><strong>Most Improved RPM (range: (month or year); month; year):</strong> <code>/racers/most_improved_rpm?range=month&month=6&year=2014&limit=5</code> (<a href="index.php/racers/most_improved_rpm.json?range=month&month=6&year=2014&limit=5&key=$daily_key">JSON</a>, <a href="index.php/racers/most_improved_rpm.js?range=month&month=6&year=2014&limit=5&key=$daily_key&callback=myCallback">JSONP</a>, <a href="index.php/racers/most_improved_rpm.xml?range=month&month=6&year=2014&limit=5&key=$daily_key">XML</a>)</code></li>
                            </ul>
                        </li>
                    </ul>

                    <h4><i class="icon-plus"></i> Races - Race Results</h4>
                    <p class="description">Get information on races and laps. Can use "next" or "current" in place of the race_id to pull information from the next or currently running race.</p>
                    <p class="description"><code>heat_status_id</code>: 0 = Not Started; 1 = Currently Running; 2 = Auto Stopped; 3 = Manually Stopped; 4 = Closed</p>
                    <p class="description">There are two ways to win, stored as <code>win_by</code> in the race -- by "position" or by fastest "laptime". Races by position's timing is started when the first person crosses the start/finish line. This is the lowest <code>amb_time</code> in the laps returned. Gaps to the leader and position in the race may be calculated by taking the racer's time and subtracting out the lowest <code>amb_time</code>.</p>
                    <ul>
                        <li><strong>Today's Races:</strong> <code>/races/races</code> (<a href="index.php/races/races.json?key=$daily_key">JSON</a>, <a href="index.php/races/races.js?key=$daily_key&callback=myCallback">JSONP</a>, <a href="index.php/races/races.xml?key=$daily_key">XML</a>)</li>
                        <li><strong>Today's Upcoming Races:</strong> <code>/races/upcoming</code> (<a href="index.php/races/upcoming.json?key=$daily_key">JSON</a>, <a href="index.php/races/upcoming.js?key=$daily_key&callback=myCallback">JSONP</a>, <a href="index.php/races/upcoming.xml?key=$daily_key">XML</a>)</li>
                        <li><strong>Races on Date:</strong> <code>/races/races.json?start=2014-01-01&end=2014-01-01</code> (<a href="index.php/races/races.json?start=2014-01-01&end=2014-01-01&key=$daily_key">JSON</a>, <a href="index.php/races/races.js?start=2014-01-01&end=2014-01-01&key=$daily_key&callback=myCallback">JSONP</a>, <a href="index.php/races/races.xml?start=2014-01-01&end=2014-01-01&key=$daily_key">XML</a>)</li>
                        <li><strong>Get next race:</strong> (defaults to track 1, offset 0) <code>/races/next</code> (<a href="index.php/races/next.json?track=1&key=$daily_key">JSON</a>, <a href="index.php/races/next.js?track=1&key=$daily_key&callback=myCallback">JSONP</a>, <a href="index.php/races/next.xml?track=1&key=$daily_key">XML</a>)</li>
                        <li><strong>Get previous race:</strong> (defaults to track 1, offset 0) <code>/races/previous</code> (<a href="index.php/races/previous.json?track=1&key=$daily_key">JSON</a>, <a href="index.php/races/previous.js?track=1&key=$daily_key&callback=myCallback">JSONP</a>, <a href="index.php/races/previous.xml?track=1&key=$daily_key">XML</a>)</li>
                        <li><strong>Get current race_id:</strong> (defaults to track 1) <code>/races/current_race_id</code> (<a href="index.php/races/current_race_id.json?track=1&key=$daily_key">JSON</a>, <a href="index.php/races/current_race_id.js?track=1&key=$daily_key&callback=myCallback">JSONP</a>, <a href="index.php/races/current_race_id.xml?track=1&key=$daily_key">XML</a>)</li>
                        <li><strong>Details on race:</strong> <code>/races/9829</code> (<a href="index.php/races/9128.json?key=$daily_key">JSON</a>, <a href="index.php/races/9128.js?key=$daily_key&callback=myCallback">JSONP</a>, <a href="index.php/races/9128.xml?key=$daily_key">XML</a>)</li>
                        <li><strong>Laps completed:</strong> <code>/races/9829/number_of_laps</code> (<a href="index.php/races/9128/number_of_laps.json?key=$daily_key">JSON</a>, <a href="index.php/races/9128/number_of_laps.js?key=$daily_key&callback=myCallback">JSONP</a>, <a href="index.php/races/9128/number_of_laps.xml?key=$daily_key">XML</a>)</li>
                        <li><strong>Details on race (limiting by racer and only laps after a certain lap_id):</strong> <code>/races/9829/laps.json?racer_id=1000002&lap_id=584079</code> (<a href="index.php/races/9829/laps.json?racer_id=1000002&lap_id=584079&key=$daily_key">JSON</a>, <a href="index.php/races/9829/laps.js?&key=$daily_key&racer_id=1000002&lap_id=584079&key=$daily_key&callback=myCallback">JSONP</a>, <a href="index.php/races/9829/laps.xml?&key=$daily_key&racer_id=1000002&lap_id=584079">XML</a>)</li>
                    </ul>
                
                    <h4><i class="icon-plus"></i> Races - Scoreboard</h4>
                    <p class="description">Get the scoreboard for a specific heat or track</p>
                    <ul>
                        <li><strong>By track_id:</strong> <code>/races/scoreboard</code> (<a href="index.php/races/scoreboard.json?track_id=1&key=$daily_key">JSON</a>, <a href="index.php/races/scoreboard.json?track_id=1&key=$daily_key&callback=myCallback">JSONP</a>, <a href="index.php/races/scoreboard.json?track_id=1&key=$daily_key">XML</a>)</li>
                        <li><strong>By heat_id:</strong> <code>/races/scoreboard</code> (<a href="index.php/races/scoreboard.json?heat_id=1&key=$daily_key">JSON</a>, <a href="index.php/races/scoreboard.json?heat_id=1&key=$daily_key&callback=myCallback">JSONP</a>, <a href="index.php/races/scoreboard.json?heat_id=1&key=$daily_key">XML</a>)</li>
                    </ul>
                    
                    <h4><i class="icon-plus"></i> Races - Stats</h4>
                    <p class="description">Find out some interesting info about the laps run during races</p>
                    <ul>
                        <li><strong>Total Laps Completed:</strong> <code>/races/total_laps</code> (<a href="index.php/races/total_laps.json?key=$daily_key">JSON</a>, <a href="index.php/races/total_laps.js?key=$daily_key&callback=myCallback">JSONP</a>, <a href="index.php/races/total_laps.xml?key=$daily_key">XML</a>)</li>
                        <li><strong>Who Did Lap #:</strong> <code>/races/lap_number/500000</code> (<a href="index.php/races/lap_number/500000.json?key=$daily_key">JSON</a>, <a href="index.php/races/lap_number/500000.js?key=$daily_key&callback=myCallback">JSONP</a>, <a href="index.php/races/lap_number/500000.xml?key=$daily_key">XML</a>)</li>
                    </ul>

                    <h4><i class="icon-plus"></i> Races - After specific time</h4>
                    <p class="description">Get a list of completed heats after a specific date and time</p>
                    <ul>
                        <li><strong>Races after specific time:</strong> <code>/races/since?&date=2014-04-01 09:00:00&limit=200</code><br/> (<a href="index.php/races/since.json?&date=2014-04-01 09:00:00&limit=200&key=$daily_key">JSON</a>,
                        <a href="index.php/races/since.js?&date=2014-04-01 09:00:00&limit=200&key=$daily_key&callback=myCallback">JSONP</a>,
                         <a href="index.php/races/since.xml?&date=2014-04-01 09:00:00&limit=200&key=$daily_key">XML</a>)
                         <br/>(Limit is an optional parameter. Defaults to 100 rows, maxes out at 500 rows.)</li>

                    </ul>

                    <h4><i class="icon-plus"></i> Races - Final positions</h4>
                    <p class="description">Find out the final positions for each racer in a finished heat</p>
                    <ul>
                        <li><strong>Final positions of heat:</strong> <code>/races/final_positions?&race_id=1000</code> (<a href="index.php/races/final_positions.json?&race_id=1000&key=$daily_key">JSON</a>,
                        <a href="index.php/races/final_positions.js?&race_id=1000&key=$daily_key&callback=myCallback">JSONP</a>,
                         <a href="index.php/races/final_positions.xml?&race_id=1000&key=$daily_key">XML</a>)</li>
                    </ul>

                    <h4><i class="icon-plus"></i> Races - Fastest Laps</h4>
                    <p class="description">Find the fastest laps. Results have many options for filtering and sorting. Supports a maximum of 100 per query.</p>
                    <ul>
                        <li><strong>By Time Period</strong>
                            <ul>
                                <li><strong>Day:</strong> <code>/races/fastest?range=day</code> (<a href="index.php/races/fastest.json?range=day&key=$daily_key">JSON</a>, <a href="index.php/races/fastest.js?range=day&key=$daily_key&callback=myCallback">JSONP</a>, <a href="index.php/races/fastest.xml?range=day&key=$daily_key">XML</a>)</li>
                                <li><strong>Week:</strong> <code>/races/fastest?range=week</code></li>
                                <li><strong>Month:</strong> <code>/races/fastest?range=month</code></li>
                                <li><strong>Year:</strong> <code>/races/fastest?range=year</code></li>
                                <li><strong>In a Date Range:</strong> <code>/races/fastest?start=2012-01-01&end=2012-01-01</code></li>
                            </ul>
                        </li>
                        <li><strong>Filter Results By</strong>
                            <ul>
                                <li><strong>Tracks (1: Rental, 2: Oval, 3: Race):</strong> <code>/races/fastest?track=1</code></li>
                                <li><strong>Speed Level (1: Adult Rental CCW; 2: Junior Rental CCW; 3-4 Not Used; 5: Event Track: 6; Adult Rental CW; 7: Junior Rental CW):</strong> <code>/races/fastest?speed_level=1</code></li>
                                <li><strong>Limt:</strong> <code>/races/fastest?limit=5</code></li>
                                <li><strong>Gender (m: Male, f: Female):</strong> <code>/races/fastest?gender=m</code></li>
                                <li><strong>Exclude Employees:</strong> <code>/races/fastest?exclude_employees=1</code></li>
                                <li><strong>Weight (light: 0-155lb, medium: 156-190lb, heavy: 191-220lb, sumo: 221+lb):</strong> <code>/races/fastest?weight=light</code></li>
                                <li><strong>Birth Date in Range:</strong> <code>/races/fastest?start_birthdate=1982-01-01&end_birthdate=1982-12-31</code></li>
                            </ul>
                        </li>
                    </ul>
                    
                    <h4><i class="icon-plus"></i> Tracks</h4>
                    <p class="description">Discover all tracks at a venue</p>
                    <ul>
                        <li><strong>All Tracks:</strong> <code>/tracks/index</code> (<a href="index.php/tracks/index.json?key=$daily_key">JSON</a>, <a href="index.php/tracks/index.js?key=$daily_key&callback=myCallback">JSONP</a>, <a href="index.php/tracks/index.xml?key=$daily_key">XML</a>)</li>
                    </ul>

                    <h4><i class="icon-plus"></i> Version</h4>
                    <p class="description">Get the current version of Club Speed</p>
                    <ul>
                        <li><strong>Get Club Speed version:</strong> <code>/version/current</code> (<a href="index.php/version/current.json?key=$daily_key">JSON</a>, <a href="index.php/version/current.js?key=$daily_key&callback=myCallback">JSONP</a>, <a href="index.php/version/current.xml?key=$daily_key">XML</a>)</li>
                        <li><strong>Get API version:</strong> <code>/version/api</code> (<a href="index.php/version/api.json?key=$daily_key">JSON</a>, <a href="index.php/version/api.js?key=$daily_key&callback=myCallback">JSONP</a>, <a href="index.php/version/api.xml?key=$daily_key">XML</a>)</li>
                    </ul>
                    
                    <h4><i class="icon-plus"></i> Channel</h4>
                    <p class="description">Get the configuration for a "Speed Screen" channel</p>
                    <ul>
                        <li><strong>Get Club Speed channel configuration:</strong> <code>/channel/:channelId</code> (<a href="index.php/channel/1.json?key=$daily_key">JSON</a>, <a href="index.php/channel/1.js?key=$daily_key&callback=myCallback">JSONP</a>, <a href="index.php/channel/1.xml?key=$daily_key">XML</a>)</li>
                    </ul>

                    <h4><i class="icon-plus"></i> Users</h4>
                    <p class="description">Attempt to login a user</p>
                    <ul>
                        <li><strong>Login (returns true or false):</strong> <code>/users/login</code> (<a href="index.php/users/login.json?username=abc&password=123&key=$daily_key">JSON</a>, <a href="index.php/users/login.js?username=abc&password=123&key=$daily_key&callback=myCallback">JSONP</a>, <a href="index.php/users/login.xml?username=abc&password=123&key=$daily_key">XML</a>)</li>
                        <li><strong>Login Admin (returns true or false):</strong> <code>/users/login</code> (<a href="index.php/users/login.json?is_admin=1&username=abc&password=123&key=$daily_key">JSON</a>, <a href="index.php/users/login.js?is_admin=1&username=abc&password=123&key=$daily_key&callback=myCallback">JSONP</a>, <a href="index.php/users/login.xml?is_admin=1&username=abc&password=123&key=$daily_key">XML</a>)</li>
                    </ul>
                    
                    <h4><i class="icon-plus"></i> Translations</h4>
                    <p class="description">Tie into Club Speed's translation database. Translations are grouped by "namespaces".</p>
                    <ul>
                        <li><strong>Retrieve by namespace:</strong> <code>/translations/getNamespace</code> (<a href="index.php/translations/getNamespace.json?namespace=Interfaces.Common&key=$daily_key">JSON</a>, <a href="index.php/translations/getNamespace.js?namespace=Interfaces.Common&key=$daily_key&callback=myCallback">JSONP</a>, <a href="index.php/translations/getNamespace.xml?namespace=Interfaces.Common&key=$daily_key">XML</a>)</li>
                        <li><strong>Retrieve by language:</strong> <code>/translations/getTranslations</code> (<a href="index.php/translations/getTranslations.json?language=en-US&key=$daily_key">JSON</a>, <a href="index.php/translations/getTranslations.js?language=en-US&key=$daily_key&callback=myCallback">JSONP</a>, <a href="index.php/translations/getTranslations.xml?language=en-US&key=$daily_key">XML</a>)</li>
                        <li><strong>Translate by key(s). Keys may be String or Array:</strong> <code>/translations/translate</code> (<a href="index.php/translations/translate.json?keys=strPoints&language=en-US&namespace=Interfaces.Common&key=$daily_key">JSON</a>, <a href="index.php/translations/translate.js?keys=strPoints&language=en-US&namespace=Interfaces.Common&key=$daily_key&callback=myCallback">JSONP</a>, <a href="index.php/translations/translate.xml?keys=strPoints&language=en-US&namespace=Interfaces.Common&key=$daily_key">XML</a>)</li>
                    </ul>
                    
                    <h4><i class="icon-plus"></i> Settings</h4>
                    <p class="description">Retrieve settings from Club Speed <strong>(most settings require a private key)</strong>. Settings are grouped and may be accessed by the entire group or by a specific group/setting pair.</p>
                    <p class="description">A special group entitled "kiosk" exists that presents a consolidated registration kiosk setting group regardless of the version of Club Speed.</p>
                    <p class="description"><strong>Other supported groups:</strong> "decoders"</p>

                    <ul>
                        <li><strong>Retrieve by group:</strong> <code>/settings/get</code> (<a href="index.php/settings/get.json?group=kiosk&key=$daily_key">JSON</a>, <a href="index.php/settings/get.js?group=kiosk&key=$daily_key&callback=myCallback">JSONP</a>, <a href="index.php/settings/get.xml?group=kiosk&key=$daily_key">XML</a>)</li>
                        <li><strong>Retrieve by group/setting pair:</strong> <code>/settings/get</code> (<a href="index.php/settings/get.json?group=MainEngine&setting=currentCulture&key=$daily_key">JSON</a>, <a href="index.php/settings/get.js?group=MainEngine&setting=currentCulture&key=$daily_key&callback=myCallback">JSONP</a>, <a href="index.php/settings/get.xml?group=MainEngine&setting=currentCulture&key=$daily_key">XML</a>)</li>
                    </ul>
                     <h4><i class="icon-plus"></i> Settings - Images</h4>
                    <p class="description">Retrieve images from Club Speed <strong>(requires private key)</strong>. Settings are grouped by app.</p>
                    <p class="description">Currently supported apps: kiosk</p>
                    <ul>
                        <li><strong>Retrieve images by app:</strong> <code>/settings/getImages</code> (<a href="index.php/settings/getImages.json?app=kiosk&key=$daily_key">JSON</a>, <a href="index.php/settings/getImages.js?app=kiosk&key=$daily_key&callback=myCallback">JSONP</a>, <a href="index.php/settings/getImages.xml?app=kiosk&key=$daily_key">XML</a>)</li>
                    </ul>

            </div><!--/span-->
          </div><!--/row-->
		  
        </div><!--/span-->
      </div><!--/row-->



    </div><!--/.container-->

    <script src="js/jquery.js"></script>
    <script src="js/bootstrap.js"></script>
    <script src="js/myresume.js"></script>

  </body>
</html>
EOH;
		die($html);
	}
	
}