<?php
require_once('vendors/swiftmailer/lib/swift_required.php');

/**
 * ClubSpeed API
 *
 * Proposed API for accessing racer, heat and scoring information
 * generated by ClubSpeed server.
 * @author Wes Ratcliff <wes@clubspeed.com>
 * @version 0.1
 */

 /**
  * /racers/search?query=Wes Ratcliff&key=test
  * /racers/search?query=wes@nolamotor.com&key=test
  * /racers/1000002?key=test
  * /racers/1000002/heats?key=test
  */
class Racers
{
    public $restler;

	function __construct(){
		header('Access-Control-Allow-Origin: *'); //Here for all /say
	}

	private function getNextCustomerId() {
		$customerIdSql = <<<EOD
DECLARE @IsRepl_On bit
SELECT @IsRepl_On = Settingvalue From Controlpanel where settingname = 'ReplicateCustomerInfo'

IF @IsRepl_On = 1
Begin
	DECLARE @LocationID int
	SELECT @LocationID = Settingvalue From Controlpanel Where Settingname = 'LocationID'	
	SELECT ISNULL(Max(CustID) + 1, (@LocationID * 1000000 + 1)) From Customers Where CustID Between (@LocationID * 1000000) and ((@LocationID + 1) * 1000000)
End
Else
Begin
	SELECT ISNULL(Max(CustID) + 1, (@LocationID * 1000000 + 1)) From Customers 
End
EOD;
		$rows = $this->run_query($customerIdSql, array());
		return $rows[0][''];
	}

	/**
	 * Create a customer
	 * @protected
	 * @param array $request_data
	 * @return array
	 */
	protected function postCreate($request_data) {

        if($_REQUEST['key'] != $GLOBALS['privateKey']) throw new RestException(412, 'Not authorized');

		/*
		$fieldMapping = array(
			'first' => 'FName',
			'last' => 'LName',
			'racerName' => 'RacerName',
			'birthDate' => 'BirthDate',
			'gender' => 'Gender',
			'email' => 'EmailAddress',
			'howDidYouHearId' => 'SourceID',
			'doNotMail' => 'DoNotMail',
			'addressLine1' => 'Address',
			'addressLine2' => 'Address2',
			'city' => 'City',
			'state' => 'State',
			'postalcode' => 'Zip',
			'country' => 'Country',
			'cellNumber' => 'Cell',
			'custom1' => 'Custom1',
			'custom2' => 'Custom2',
			'custom3' => 'Custom3',
			'custom4' => 'Custom4',
			'waiverStatus' => 'Status1',
			'waiver1TemplateSigned' => 'Waiver',
			'waiver2TemplateSigned' => 'Waiver2',
			'facebookId' => '',
			'facebookToken' => '',
			'signature' => array('type', 'data'),
			'photo' => array('type', 'data'),
			);
		*/

		// Get customer id
		$customerId = $this->getNextCustomerId();

		/*
		Example posting
		{
			"birthdate": "1985-03-13",
			"mobilephone": "7142705683",
			"howdidyouhearaboutus": "billboard",
			"firstname": "Brian",
			"lastname": "Chuchua",
			"racername": "Brian Chuchua",
			"email": "brian@clubspeed.com",
			"donotemail": true,
			"profilephoto": "data:image/jpeg;base64,blahblah",
			"signaturephoto": "data:image/png;base64,blahblah",
		    "gender": blahblah,
		    "BusinessName": blahblah
		}
		*/

		// Create customer
		// Create a customer flow from Shakib: Get ID, Check for Unicode, Set Status Flags (based on actions defined), Send Welcome Email, Check for Duplicates, Set privacy_4 = true (if using Facebook)

		// TODO -- Handle setting status fields
		// TODO -- Handle saving SQL

        $genderCode = 0;
        if (!empty($request_data['gender']))
        {
            switch ($genderCode)
            {
                case "male":
                    $genderCode = 1;
                    break;
                case "female":
                    $genderCode = 2;
                    break;
            }
        }

		$tsql = "INSERT INTO Customers ( CustID, RacerName, EmailAddress, DoNotMail, FName, LName, SourceID, BirthDate, Cell, IgnoreDOB, Gender, Status1, Address, Address2, Country, City, State, Zip ) OUTPUT INSERTED.CustID VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )";
		$params = array($customerId,
			@$request_data['racername'],
			@$request_data['email'],
			@$request_data['donotemail'],
			@$request_data['firstname'],
			@$request_data['lastname'],
			@$request_data['howdidyouhearaboutus'],
            empty($request_data['birthdate']) ? null : date($GLOBALS['dateFormat'], strtotime(date('Y-m-d', strtotime($request_data['birthdate']))) + 24*60*60),
			@$request_data['mobilephone'],
			empty($request_data['birthdate']) ? true : false,
            $genderCode,
            2, //2 in Status1 means "Signed Waiver"
            isset($request_data['Address']) ? $request_data['Address'] : '',
            isset($request_data['Address2']) ? $request_data['Address2'] : '',
            isset($request_data['Country']) ? $request_data['Country'] : '',
            isset($request_data['City']) ? $request_data['City'] : '',
            isset($request_data['State']) ? $request_data['State'] : '',
            isset($request_data['Zip']) ? $request_data['Zip'] : '',
			);

        $rows = $this->run_query($tsql, $params);

		// Create photo
		// TODO -- Handle resize
		if(!empty($request_data['profilephoto'])) {
			$picturePath = empty($GLOBALS['customerPictureImagePath']) ? 'C:\ClubSpeed\CustomerPictures' : $GLOBALS['customerPictureImagePath'];
			file_put_contents($picturePath . DIRECTORY_SEPARATOR . $customerId . '.jpg',
				$this->base64_to_img($request_data['profilephoto']));
		}

        // Create signature, if present
        if(!empty($request_data['signaturephoto'])) {
            if ($request_data['isMinor'] == "true")
            {
                $picturePath = empty($GLOBALS['customerMinorSignatureImagePath']) ? 'C:\ClubSpeed\CustomerSignatures2' : $GLOBALS['customerMinorSignatureImagePath'];
                file_put_contents($picturePath . DIRECTORY_SEPARATOR . $customerId . '.jpg',
                    $this->base64_to_img($request_data['signaturephoto']));
            }
            else
            {
                $picturePath = empty($GLOBALS['customerAdultSignatureImagePath']) ? 'C:\ClubSpeed\CustomerSignatures' : $GLOBALS['customerAdultSignatureImagePath'];
                file_put_contents($picturePath . DIRECTORY_SEPARATOR . $customerId . '.jpg',
                    $this->base64_to_img($request_data['signaturephoto']));
            }
        }

        // Create waiver
        if ($request_data['isMinor'] == "true")
        {
            $waiverPath = empty($GLOBALS['customerMinorWaiverImagePath']) ? 'C:\ClubSpeed\CustomerWaivers2' : $GLOBALS['customerMinorWaiverImagePath'];
            $termsText = $request_data['Waiver2'];
        }
        else
        {
            $waiverPath = empty($GLOBALS['customerAdultWaiverImagePath']) ? 'C:\ClubSpeed\CustomerWaivers' : $GLOBALS['customerAdultWaiverImagePath'];
            $termsText = $request_data['Waiver1'];
        }

        $subheaderData = array("Dated" => date("l, F j, Y m/d/y"), "Business" => $request_data['BusinessName'],
            "Participant" => $request_data['firstname'] . ' ' . $request_data['lastname'] /*array("Andrew Dodge","13000 Quailwood Rd","Midlothian, Virginia 23112")*/,
            "License #" => "",
            "Birthdate" => $request_data['birthdate'], "Phone" => $request_data['mobilephone'],
            "Email" => $request_data['email'], "CustID" => $customerId);

        $waivers = $this->createWaiverImages($termsText,$subheaderData,$request_data['signaturephoto']);

        $currentPage = 1;
        foreach($waivers as $currentWaiverPage)
        {
            file_put_contents($waiverPath . DIRECTORY_SEPARATOR . $customerId . '-' . $currentPage .  '.jpg',
                $this->base64_to_img($currentWaiverPage));
            $currentPage++;
        }


        //Welcome e-mail
        if ($request_data['email'] != '') //If we have an e-mail address to send to
        {
            //Get welcome e-mail settings
            $tsql = "SELECT SettingName, SettingValue FROM ControlPanel WHERE TerminalName = 'MainEngine' AND " .
                "(SettingName = 'SendWelcomeMail' OR SettingName = 'EmailWelcomeFrom' OR SettingName = 'SMTPServerUseAuthentiation' " .
                "OR SettingName = 'SMTPServer' " .
                "OR SettingName = 'SMTPServerPort' " .
                "OR SettingName = 'SMTPServerAuthenticationUserName' " .
                "OR SettingName = 'SMTPServerAuthenticationPassword' " .
                "OR SettingName = 'SMTPServerUseSSL')";
            $results = $this->run_query($tsql);
            $settings = array();
            foreach($results as $currentSetting)
            {
                $settings[$currentSetting['SettingName']] = $currentSetting['SettingValue'];
            }

            if (strtolower($settings['SendWelcomeMail']) == "true") //If the track would like to send welcome e-mails
            {
                //Get the mail template
                $tsql = "SELECT Text, Subject FROM MailTemplate";
                $emailStrings = $this->run_query($tsql);
                if (array_key_exists(0,$emailStrings)) //If a mail template is defined, send an e-mail
                {
                    $emailStrings['Subject'] = $emailStrings[0]['Subject'];
                    $emailStrings['Text'] = $emailStrings[0]['Text'];

                    //Replace any placeholders with their values
                    $tagsToReplace = array('##FIRSTNAME##','##LASTNAME##','##EMAIL##','##TIME##','##RACERNAME##');
                    $dataToInsert = array($request_data['firstname'],$request_data['lastname'],$request_data['email'],
                        date("F j, Y, g:i a"),$request_data['racername']);
                    $emailStrings['Subject'] = str_replace($tagsToReplace,$dataToInsert,$emailStrings['Subject']);
                    $emailStrings['Text'] = str_replace($tagsToReplace,$dataToInsert,$emailStrings['Text']);

                    //Send the e-mail
                    $message = Swift_Message::newInstance()
                        ->setSubject($emailStrings['Subject'])
                        ->setFrom(array($settings['EmailWelcomeFrom'] => $request_data['BusinessName']))
                        ->setTo(array($request_data['email'] => $request_data['firstname'] . ' ' . $request_data['lastname']))
                        ->setBody($emailStrings['Text'],'text/html');

                    if (!isset($settings['SMTPServerPort']))
                    {
                        $settings['SMTPServerPort'] = "25";
                    }
                    if (isset($settings['SMTPServerUseAuthentiation']) && strtolower($settings['SMTPServerUseAuthentiation']) == "true")
                    {
                        if (isset($settings['SMTPServerUseSSL']) && strtolower($settings['SMTPServerUseSSL']) == "true")
                        {
                            $transport = Swift_SmtpTransport::newInstance($settings['SMTPServer'], $settings['SMTPServerPort'], 'ssl')
                                ->setUsername($settings['SMTPServerAuthenticationUserName'])
                                ->setPassword($settings['SMTPServerAuthenticationPassword']);
                        }
                        else
                        {
                            $transport = Swift_SmtpTransport::newInstance($settings['SMTPServer'], $settings['SMTPServerPort'])
                                ->setUsername($settings['SMTPServerAuthenticationUserName'])
                                ->setPassword($settings['SMTPServerAuthenticationPassword']);
                        }
                    }
                    else
                    {
                        $transport = Swift_SmtpTransport::newInstance($settings['SMTPServer'], $settings['SMTPServerPort']);
                    }

                    $mailer = Swift_Mailer::newInstance($transport);
                    try
                    {
                        $result = $mailer->send($message,$failures);
                    }
                    catch (Exception $e)
                    {
                        return array('Exception' => $e->getMessage(), 'Settings' => $settings);
                    }
                }
            }
        }

        // TODO -- Trigger logs insertion for tracks with replication enabled

		return array('customerId' => $customerId);
	}

	function base64_to_img($base64_string) {
			$data = explode(',', $base64_string);

			return base64_decode($data[1]);
	}

    function createWaiverImages($termsText,$subheaderData,$signatureImage)
    {
        //Dimension variables
        $waiverWidth = 800;
        $waiverHeight = 1100;
        $waiverMargin = 20;
        $headerHeight = 60;
        $subheaderHeight = 170;
        $termsHeight = 640;
        $footerHeight = 190;
        $subheaderLeftMargin = 60;

        //Text format variables
        $font = 'fonts/arial.ttf';
        $fontBold = 'fonts/arialbd.ttf';
        $textPadding = 10;
        $termsFontSize = 10;
        $headerFontSize = 12;
        $subheaderFontSize = 11;
        $termsHeaderFontSize = 12;
        $footerLabelsFontSize = 12;
        $footerDataFontSize = 11;

        //Key default strings
        $headerText = "Express Assumption of risk, complete waiver and agreement not to sue, and indemnity agreement"; //TODO: That capital "A". Get rid of it. Ugly, ugly.
        $termsHeaderText = "READ THIS CAREFULLY - IT AFFECTS YOUR LEGAL RIGHTS";
        $footerLabelParticipantText = "Participant  X";
        $footerLabelDateText = "Date";
        $dateForSignatureAreaText = date("l, F j, Y")/*"Monday, June 16, 2014"*/;
        $pageText = "Page";
        $ofText = "of";

        //Key data models
        $waivers = array(); //The actual waiver pages, in base64 format, that are returned to the user
        $waiverText = array(); //The waiver text. Each index is a page. Each page is split into lines.
        $currentPage = 1;

        //Determine the height of the entirety of the waiver text - is it more than a single page?
        $termsTextWrapped = $this->wrap($termsFontSize,0,$font,$termsText,$waiverWidth-$waiverMargin*2-$textPadding*4);
        $termsTextWrappedBox = imagettfbbox($termsFontSize, 0, $font, $termsTextWrapped);
        $heightOfTermsText = abs($termsTextWrappedBox[5] - $termsTextWrappedBox[1]);

        if ($heightOfTermsText > $termsHeight) //If the waiver text requires more than one page, split it up for each page
        {
            $allTermsLines = explode("\n",$termsTextWrapped);
            $heightPerLine = $heightOfTermsText / sizeof($allTermsLines);
            $numberOfLinesPerPage = floor( ($termsHeight-30) / $heightPerLine);

            $currentTermsPage = array();
            while (sizeof($allTermsLines) > 0)
            {
                array_push($currentTermsPage,array_shift($allTermsLines));
                if (sizeof($currentTermsPage) == $numberOfLinesPerPage || sizeof($allTermsLines) == 0)
                {
                    array_push($waiverText,$currentTermsPage);
                    $currentTermsPage = array();
                }
            }
        }
        else //Else, we'll just process it as a single-page waiver
        {
            $allTermsLines = explode("\n",$termsTextWrapped);
            array_push($waiverText,$allTermsLines);
        }

        foreach($waiverText as $currentPageWaiverText) //For every waiver page
        {
            //Create the canvas on which to draw the waiver
            $waiverCanvas = imagecreatetruecolor($waiverWidth,$waiverHeight);

            //Color definitions for the current canvas
            $white = imagecolorallocate($waiverCanvas, 255, 255, 255);
            $black = imagecolorallocate($waiverCanvas, 0, 0, 0);

            //Fill the entire waiver with a white background
            imagefilledrectangle($waiverCanvas,0,0,$waiverWidth,$waiverHeight,$white);

            //Draw a black-bordered rectangle to serve as the waiver's inner body, with the specified margin on all sides
            imagerectangle($waiverCanvas,$waiverMargin,$waiverMargin,$waiverWidth - $waiverMargin,$waiverHeight - $waiverMargin,$black);

            //Draw the header line
            imageline($waiverCanvas,0+$waiverMargin,$headerHeight+$waiverMargin,$waiverWidth-$waiverMargin,$headerHeight+$waiverMargin,$black);

            //Determine how to center the header text
            $headerTextBox = imagettfbbox($headerFontSize, 0, $fontBold, $headerText);
            $headerTextBoxWidth = $headerTextBox[2];
            $headerXCoordinate = ceil(($waiverWidth - $headerTextBoxWidth) / 2);
            $headerYCoordinate = $headerHeight/2 + $headerFontSize/2 + $waiverMargin;

            //Write the header text
            imagettftext($waiverCanvas, $headerFontSize, 0, $headerXCoordinate, $headerYCoordinate, $black, $fontBold, $headerText);

            //Draw the subheader line
            imageline($waiverCanvas,0+$waiverMargin,$subheaderHeight+$headerHeight+$waiverMargin,$waiverWidth-$waiverMargin,$subheaderHeight+$headerHeight+$waiverMargin,$black);

            //Determine subheader data starting positions
            $subheaderStartXCoordinate = $subheaderLeftMargin + $waiverMargin + $textPadding;
            $subheaderStartYCoordinate = $headerHeight+$waiverMargin+$subheaderFontSize+$textPadding;
            $currentX = $subheaderStartXCoordinate;
            $currentY = $subheaderStartYCoordinate;
            $currentColumn = 1;
            $currentRow = 1;

            //For every piece of subheader data, render it in the subheader area, bolding the first three data values
            foreach($subheaderData as $field => $value)
            {
                imagettftext($waiverCanvas, $subheaderFontSize, 0, $currentX, $currentY, $black, $font, $field); //Write the field label

                if (is_array($value)) //If there's more than one value for that label, write them beneath one another
                {
                    $firstValueNeedsBolding = true;
                    foreach($value as $currentValue)
                    {
                        imagettftext($waiverCanvas, $subheaderFontSize, 0, $currentX + 100, $currentY, $black, $currentRow <= 3 && $firstValueNeedsBolding? $fontBold : $font, $currentValue);
                        $currentY = $currentY + $subheaderFontSize + $textPadding;
                        $firstValueNeedsBolding = false;
                    }
                    $currentY = $currentY - ($subheaderFontSize + $textPadding);
                }
                else //If there's just value, write the value for that label
                {
                    imagettftext($waiverCanvas, $subheaderFontSize, 0, $currentX + 100, $currentY, $black, $currentRow <= 3 ? $fontBold : $font, $value);
                }
                $currentY = $currentY + $subheaderFontSize + $textPadding;
                if ($currentColumn < 2 && $currentRow >= sizeof($subheaderData)/2 || $currentY > $subheaderHeight+$headerHeight+$waiverMargin) //If we're out of room in the first column
                {
                    $currentX = $currentX + $waiverWidth/2 - $waiverMargin - $subheaderLeftMargin/2; //Move on to the second column
                    $currentY = $subheaderStartYCoordinate + ($subheaderFontSize + $textPadding)*2;
                    $currentColumn += 1;
                }
                $currentRow += 1;
            }

            //Draw the terms header
            $termsHeaderXCoordinate = 0+$waiverMargin+$textPadding*2;
            $termsHeaderYCoordinate = $subheaderHeight+$headerHeight+$waiverMargin+$textPadding*2;
            imagettftext($waiverCanvas, $termsHeaderFontSize, 0, $termsHeaderXCoordinate, $termsHeaderYCoordinate, $black, $fontBold, $termsHeaderText);

            //Draw the terms text for the current page
            $termsStartXCoordinate = 0+$waiverMargin+$textPadding*2;
            $termsStartYCoordinate = $subheaderHeight+$headerHeight+$waiverMargin+$textPadding*5;
            $currentPageWaiverText = implode($currentPageWaiverText,"\n");
            imagettftext($waiverCanvas, $termsFontSize, 0, $termsStartXCoordinate, $termsStartYCoordinate, $black, $font, $currentPageWaiverText);

            //Draw the footer line
            $footerStartXCoordinate = 0+$waiverMargin;
            $footerStartYCoordinate = $termsHeight+$subheaderHeight+$headerHeight+$waiverMargin;
            imageline($waiverCanvas,$footerStartXCoordinate,$footerStartYCoordinate,$waiverWidth-$waiverMargin,$footerStartYCoordinate,$black);

            //Draw the footer text and lines
            $footerLabelsStartXCoordinate = $waiverMargin + $textPadding*2;
            $footerLabelsStartYCoordinate = $footerHeight/2 + $footerStartYCoordinate + $textPadding*2;
            imagettftext($waiverCanvas, $footerLabelsFontSize, 0, $footerLabelsStartXCoordinate, $footerLabelsStartYCoordinate, $black, $fontBold, $footerLabelParticipantText);
            $participantTextBox = imagettfbbox($footerLabelsFontSize, 0, $fontBold, $footerLabelParticipantText);
            $participantTextBoxWidth = $participantTextBox[2];

            //Paste the waiver signature, if present
            if ($signatureImage != null)
            {
                imagecopy($waiverCanvas,($this->base64_to_imageresource($signatureImage)),$footerLabelsStartXCoordinate+$participantTextBoxWidth - $textPadding
                    ,$footerLabelsStartYCoordinate + $textPadding*2-80,0,0,160,90);
            }

            //Draw the waiver signature line
            imageline($waiverCanvas,$footerLabelsStartXCoordinate+$participantTextBoxWidth - $textPadding,$footerLabelsStartYCoordinate + $textPadding*2,$waiverWidth/2,$footerLabelsStartYCoordinate + $textPadding*2,$black);

            //Draw the date line
            imageline($waiverCanvas,$waiverWidth/2 + $waiverMargin*2,$footerLabelsStartYCoordinate + $textPadding*2,$waiverWidth - $waiverMargin*2,$footerLabelsStartYCoordinate + $textPadding*2,$black);

            //Write the date label text
            imagettftext($waiverCanvas, $footerLabelsFontSize, 0, $waiverWidth/2 + $waiverMargin*2, $footerLabelsStartYCoordinate + $textPadding*4, $black, $fontBold, $footerLabelDateText);

            //Write the date value text
            imagettftext($waiverCanvas, $footerDataFontSize, 0, $waiverWidth/2 + $waiverMargin*2 + $textPadding*9, $footerLabelsStartYCoordinate + $textPadding, $black, $font, $dateForSignatureAreaText);

            //Generate the current page number text

            $pageText = $currentPage . " " . $ofText .  " " . sizeof($waiverText);

            //Determine how to center the page number text
            $pageTextBox = imagettfbbox($footerDataFontSize, 0, $font, $pageText);
            $pageTextBoxWidth = $pageTextBox[2];
            $pageXCoordinate = ceil(($waiverWidth - $pageTextBoxWidth) / 2);
            $pageYCoordinate = $footerLabelsStartYCoordinate + $textPadding*7;

            //Write the page number text
            imagettftext($waiverCanvas, $footerDataFontSize, 0, $pageXCoordinate, $pageYCoordinate, $black, $font, $pageText);

            $currentPage += 1;

            //Convert the image resource to a jpg
            ob_start();
            imagejpeg($waiverCanvas,null,90);
            $waiverImage = ob_get_contents();
            ob_end_clean();

            //Convert the jpeg to base64
            $waiverImageBase64 = 'data:image/' . 'jpeg' . ';base64,' . base64_encode($waiverImage);

            array_push($waivers,$waiverImageBase64);

        }

/*        foreach($waivers as $currentWaiver)
        {
            echo "<img src='$currentWaiver'>'";
        }


        die();*/
        return $waivers;

    }

    function base64_to_imageresource($base64_string) {
        $data = explode(',', $base64_string);

        return imagecreatefromstring(base64_decode($data[1]));
    }

    function wrap($fontSize, $angle, $fontFace, $string, $width){

        return wordwrap($string,110); //Hacky way of gaining performance

        /*      Original/more accurate function:
            //Source: http://www.php.net/manual/en/function.imagettftext.php#89505
                  $ret = "";

                $arr = explode(' ', $string);

                foreach ( $arr as $word ){

                    $teststring = $ret.' '.$word;
                    $testbox = imagettfbbox($fontSize, $angle, $fontFace, $teststring);
                    if ( $testbox[2] > $width ){
                        $ret.=($ret==""?"":"\n").$word;
                    } else {
                        $ret.=($ret==""?"":' ').$word;
                    }
                }

                return $ret;*/
    }

	/**
	 * Find a racer by racer name
	 * @protected
	 * @param string nickname
	 * @return array
	 */
	protected function search() {
		if(empty($_GET['query'])) throw new RestException(412,'Please provide a search query via ?query=your_query_here');

		switch(@$_GET['field']) {

			case 'email':
				$tsql = "SELECT * FROM Customers WHERE EmailAddress = ? AND Deleted <> 'True'";
				$params = array(&$_GET['query']);
				break;

			default:
				$tsql = "SELECT * FROM Customers WHERE (RacerName LIKE ? OR EmailAddress LIKE ? OR FName LIKE ? OR LName LIKE ?) AND Deleted <> 'True'";
				$_GET['query'] = '%' . $_GET['query'] . '%';
				$params = array(&$_GET['query'], &$_GET['query'], &$_GET['query'], &$_GET['query']);
				break;
		}

		$rows = $this->run_query($tsql, $params);

		$output = array();

		foreach($rows as $row) {
			$output[] = array('id' => $row['CustID'],
							'name' => array('nickname' => $row['RacerName'],
							'first' => $row['FName'],
							'last'  => $row['LName']),
							'rpm'       => $row['RPM'],
							'created_at' => date($GLOBALS['dateFormat'], strtotime($row['AccountCreated'])),
							);

		}
		return array('racers' => $output);
	}

	protected function index($racer_id, $sub = null) {
		if($racer_id == 'valid') return $this->valid($_REQUEST['email'], $_REQUEST['racerName']);
		if($racer_id == 'create') return $this->create($_REQUEST);
		if($racer_id == 'toprpm') return $this->top_rpm();
		if($racer_id == 'last_updated' && $_REQUEST['key'] == $GLOBALS['privateKey']) return $this->last_updated($_REQUEST['start'], $_REQUEST['end'], @$_REQUEST['limit']);
		if($racer_id == 'by_id' && $_REQUEST['key'] == $GLOBALS['privateKey']) return $this->by_id($_REQUEST['start'], @$_REQUEST['limit']);
		if($racer_id == 'update_unsubscribed' && $_REQUEST['key'] == $GLOBALS['privateKey']) return $this->update_unsubscribed($_REQUEST['email']);
		if($racer_id == 'most_improved_rpm') return $this->most_improved_rpm($_REQUEST);
		if(!is_numeric($racer_id)) throw new RestException(412,'Not a valid racer id');

		if($sub != null) {
			switch($sub) {
				case 'races':
					return $this->races($racer_id);
					break;
			}
		} else {
			return $this->racer($racer_id);
		}
	}

	/**
	 * Most Improved RPM
	 * @protected
	 * @param array $request_data
	 * @return array
	 */

	protected function most_improved_rpm($params) {
		$limit = empty($params['limit']) ? 50 : (int)$params['limit'];
		switch(@$params['range']) {
			case 'month':
				$month = empty($params['month']) ? date('n') : (int)$params['month'];
				$year  = empty($params['year']) ? date('Y') : (int)$params['year'];
				$tsql_params = $month . ', ' . $year . ', ' . $limit;
				break;
			case 'year':
				$year = empty($params['year']) ? date('Y') : (int)$params['year'];
				$tsql_params = '0, ' . $year . ', ' . $limit;
				break;
			default:
				throw new RestException(412,'Not a valid range (Must be "month" or "year")');
		}
		
		// TODO Add filtering by Speed Level
		
		$tsql = "GetMostImproveRPM " . $tsql_params;
		$rows = $this->run_query($tsql, array());
		
		foreach($rows as $key => $value) {
			$rows[$key] = array('rpmChange' => $value['RPMDiff'], 'nickname' => $value['RacerName'], 'rpm' => $value['RPM']);
		}
		
		return $rows;
	}

	/**
	 * Get a racer's information
	 * @protected
	 * @param integer $customerId
	 * @return array
	 */
	protected function racer($customerId) {
		if(!is_numeric($customerId)) throw new RestException(412,'Not a valid number');

		$tsql = "SELECT TOP (1) * FROM Customers WHERE CustID = ?";

		$params = array(&$customerId);

		$rows = $this->run_query($tsql, $params);

		$output = array();

		foreach($rows as $row) {
			$output = array('id' => $row['CustID'],
							'name' => array('nickname' => $row['RacerName'],
							'first' => $row['FName'],
							'last'  => $row['LName']),
							'rpm'       => $row['RPM'],
							'created_at' => date($GLOBALS['dateFormat'], strtotime($row['AccountCreated'])),
							'visits' => $row['TotalVisits'],
							'races'  => $row['TotalRaces'],
							//'row' => $row
							);

		}

		return array('racer' => $output);
	}

	/**
	 * See if a user is valid -- for Elite Karting UK
	 * @protected
	 * @param string $email
	 * @param string $racerName
	 * @return array
	 */
	protected function valid($email, $racerName) {

		$tsql = "SELECT c.CustID, c.FName, c.LName, c.RacerName, c.EmailAddress FROM Customers c LEFT JOIN Memberships m ON c.CustID = m.CustID WHERE c.EmailAddress = ? AND c.RacerName = ? AND c.Deleted = 0"; //  AND m.ExpirationDate > GETDATE() AND m.MembershipTypeID IN (2,3,4)

		$params = array(&$email, &$racerName);

		$rows = $this->run_query($tsql, $params);
		$output = array(count($rows) > 0);

		return array('valid' => $output);
	}

	/**
	 * Get the list of races a racer has participated in
	 * @protected
	 * @param integer $customerId
	 * @return array
	 */
	protected function races($customerId) {

		if(!is_numeric($customerId)) throw new RestException(412,'Racer ID is not a valid number');

		$tsql = <<<EOD
		IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HeatMain' AND COLUMN_NAME = 'NumberOfCadetReservation')
        BEGIN
            EXEC( 'SELECT     hm.HeatNo, hm.TrackNo, ht.HeatTypeName, t.Description AS TrackName, hm.ScheduledTime, hm.HeatTypeNo, hm.LapsOrMinutes, hm.HeatStatus, hm.EventRound, hm.Begining, hm.Finish, hm.WinBy, hm.RaceBy,
                          hm.ScheduleDuration, hm.PointsNeeded, hm.SpeedLevel, hm.HeatColor, hm.NumberOfReservation, hm.MemberOnly, hm.HeatNotes, hm.ScoreID, hm.RacersPerHeat,
                          hm.NumberOfCadetReservation, hm.CadetsPerHeat, hd.HeatNo AS Expr1, hd.CustID, hd.AutoNo, hd.LineUpPosition, hd.GroupID, hd.RPM, hd.PointHistoryID,
                          hd.FirstTime, hd.UserID, hd.FinishPosition, hd.GroupFinishPosition, hd.RPMDiff, hd.PositionEditedDate, hd.HistoryAutoNo, hd.Scores, hd.TimeAdded,
                          hd.AssignedtoEntitleHeat
                        FROM HeatMain AS hm LEFT OUTER JOIN
                                              HeatDetails AS hd ON hm.HeatNo = hd.HeatNo LEFT JOIN Tracks t ON hm.TrackNo = t.TrackNo
                        LEFT JOIN HeatTypes ht ON hm.HeatTypeNo = ht.HeatTypeNo
                        WHERE (hd.CustID = $customerId)' )
        END
        ELSE
        BEGIN
            EXEC( 'SELECT     hm.HeatNo, hm.TrackNo, ht.HeatTypeName, t.Description AS TrackName, hm.ScheduledTime, hm.HeatTypeNo, hm.LapsOrMinutes, hm.HeatStatus, hm.EventRound, hm.Begining, hm.Finish, hm.WinBy, hm.RaceBy,
                          hm.ScheduleDuration, hm.PointsNeeded, hm.SpeedLevel, hm.HeatColor, hm.NumberOfReservation, hm.MemberOnly, hm.HeatNotes, hm.ScoreID, hm.RacersPerHeat,
                          hd.HeatNo AS Expr1, hd.CustID, hd.AutoNo, hd.LineUpPosition, hd.GroupID, hd.RPM, hd.PointHistoryID,
                          hd.FirstTime, hd.UserID, hd.FinishPosition, hd.GroupFinishPosition, hd.RPMDiff, hd.PositionEditedDate, hd.HistoryAutoNo, hd.Scores, hd.TimeAdded
                        FROM HeatMain AS hm LEFT OUTER JOIN
                                              HeatDetails AS hd ON hm.HeatNo = hd.HeatNo LEFT JOIN Tracks t ON hm.TrackNo = t.TrackNo
                        LEFT JOIN HeatTypes ht ON hm.HeatTypeNo = ht.HeatTypeNo
                        WHERE (hd.CustID = $customerId)' )
        END
EOD;

		$rows = $this->run_query($tsql);

		$output = array();

		foreach( $rows as $row)
		{
			  $output[] = array('id' => $row['HeatNo'],
			  				'track_id' => $row['TrackNo'],
							'heat_type_id' => $row['HeatTypeNo'],
							'heat_name' => $row['HeatTypeName'],
							'track_name' => $row['TrackName'],
							'speed_level_id' => $row['SpeedLevel'],
							'starts_at' => date($GLOBALS['dateFormat'] . ' H:i:s', strtotime($row['ScheduledTime'])),
							'racer_id' => $row['CustID'],
							'finish_position' => $row['FinishPosition'],
							'rpm' => $row['RPM'],
							//'row' => $row
							);
		}

		return array('heats' => $output);
	}

	protected function update_unsubscribed($email) {

		$output = array('No updates for ' . $email);

		// Look for customer, if exists and donotmail = 0
		$tsql_params = array($email);
		$tsql = "SELECT custid, emailaddress, donotmail FROM customers WHERE emailaddress = ?";
		$rows = $this->run_query($tsql, $tsql_params);

		//echo 'Found ' . count($rows);

		if(count($rows) > 0) {
			foreach($rows as $customer) {
				if($customer['donotmail'] == 0) {
					// Update customer row and insert trigger log

					// Set donotmail = 0
					$tsql_params = array($customer['custid']);
					$tsql = "UPDATE Customers SET donotmail = '1' WHERE CustId = ?";
					//echo $tsql;
					//print_r($tsql_params);
					$rows = $this->run_query($tsql, $tsql_params);
					print_r($rows);

					// Insert into triggerlog so that it replicates
					$tsql_params = array($customer['custid']);
					$tsql = "INSERT INTO triggerlogs (custid, lastupdated, tablename, type, deleted) VALUES (?, GETDATE(), 'Customers', 'Insert/Update', 0)";
					//echo $tsql;
					//print_r($tsql_params);
					$rows = $this->run_query($tsql, $tsql_params);

					$output = array('Updated ' . $email);
				}
			}
		}
		return $output;
	}

	protected function last_updated($start, $end, $limit = 1000) {

		$limit = empty($limit) || !is_numeric($limit) ? 1000 : $limit;

		$tsql_params = array($start, $end);

		$tsql = "select top($limit) custid, birthdate, phonenumber, (custid/1000000) AS locationid, membershipstatus, membershiptextlong AS membershiptext, cell, fname, lname, racername, birthdate, gender, emailaddress, address, address2, city, state, zip, country rpm, accountcreated, lastvisited, totalvisits, totalraces, donotmail from customers c where emailaddress <> '' and deleted = 0 and isemployee = 0 and isgiftcard = 0 AND lastVisited between ? and ? ORDER BY lastVisited";

		$racers = $this->run_query($tsql, $tsql_params);

		foreach($racers as $id => $racer) {
			
			// Add memberships
			$racers[$id]['memberships'] = array();
			$memberships = $this->run_query("GetCustomerMemberships {$racer['custid']}", array());
			foreach($memberships as $membership) {
				$racers[$id]['memberships'][] = array('name' => $membership['Description'], 'expiration' => $membership['ExpirationDate']);
			}
			
			// Add points
			$points = $this->run_query("GetCustomerStandardPoints {$racer['custid']}", array());
			$racers[$id]['points'] = floatval($points[0]['Points']);
			
			// Add cell phone consent and date
			$racers[$id]['cell_consent_given'] = empty($racer['cell']) ? false : true;
			$racers[$id]['cell_consent_date']  = empty($racers[$id]['cell_consent_given']) ? null : $racer['accountcreated'];
			
			// Add email consent and date
			$racers[$id]['email_consent_given'] = ($racer['donotmail'] == 1) ? false : true;
			$racers[$id]['email_consent_date']  = empty($racers[$id]['email_consent_given']) ? null : $racer['accountcreated'];
			
		}

		return array('racers' => $racers);
	}

	/**
	 * Find racers by ID
	 * @protected
	 * @param integer $customerId
	 * @return array
	 */
	protected function by_id($startId, $limit = null) {
		if($_REQUEST['key'] != $GLOBALS['privateKey'])
					throw new RestException(412,'Not authorized');
		$limit = empty($limit) || !is_numeric($limit) ? 1000 : $limit;

		$tsql_params = array($startId);

		$tsql = "select top($limit) custid, birthdate, cell, fname, lname, racername, birthdate, gender, emailaddress, zip,rpm, accountcreated, lastvisited, totalvisits, totalraces, donotmail  from customers where emailaddress <> '' and deleted = 0 and isemployee = 0 and isgiftcard = 0 AND custid > ? ORDER BY custid";

		$rows = $this->run_query($tsql, $tsql_params);

		return array('racers' => $rows);
	}

	protected function top_rpm() {
		//if(empty($_GET['query'])) throw new RestException(412,'Please provide a search query via ?query=your_query_here');

		$tsql_params = array();
		$tsql_gender = '';


		// Limit query
		if(isset($_GET['limit']) && is_numeric($_GET['limit'])) {
			if($_GET['limit'] > 100) throw new RestException(412,'Cannot return more than 100 rows');
			//$tsql_params[] = (int)$_GET['limit'];
			$limit = (int)$_GET['limit'];
		} else {
			//$tsql_params[] = 50;
			$limit = 50;
		}

		// Sort by gender
		if(isset($_GET['gender'])) {
			$genders = array('m' => 1, 'f' => 2);
			if(!in_array(strtolower($_GET['gender']), array('m', 'f'))) throw new RestException(412,'Invalid gender given');
			$tsql_gender = 'AND Gender = ?';
			$tsql_params[] = &$genders[strtolower($_GET['gender'])];
		}

		// TODO Add filtering by speedlevel

		$tsql = "SELECT TOP(".$limit.") * FROM Customers WHERE RPM <> 10000 $tsql_gender AND Deleted <> 'True' ORDER BY RPM DESC";

		$rows = $this->run_query($tsql, $tsql_params);

		$output = array();

		foreach($rows as $row) {
			$output[] = array('id' => $row['CustID'],
							'name' => array('nickname' => $row['RacerName'],
							'first' => $row['FName'],
							'last'  => $row['LName']),
							'rpm'       => $row['RPM'],
							'created_at' => date($GLOBALS['dateFormat'], strtotime($row['AccountCreated'])),
							);

		}
		return array('racers' => $output);
	}


	private function run_query($tsql, $params = array()) {

		// Connect
		try {
			$conn = new PDO( "sqlsrv:server=(local) ; Database=ClubSpeedV8", "", "");
			$conn->setAttribute( PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION );

			// Prepare statement
			$stmt = $conn->prepare($tsql);

			// Execute statement
			$stmt->execute($params);

			// Put in array
			$output = $stmt->fetchAll(PDO::FETCH_ASSOC);

		} catch(Exception $e) {
			die( print_r( $e->getMessage()) );
		}

		return $output;
	}

}