<?php
/**
 * ClubSpeed API
 * 
 * Proposed API for accessing racer, heat and scoring information
 * generated by ClubSpeed.
 * @author Wes Ratcliff <wes@clubspeed.com>
 * @version 0.1
 */
 
 /**
  * /subaru/
  */
class Subaru
{
    public $restler;
    
    function __construct(){
        header('Access-Control-Allow-Origin: *'); //Here for all /say
    }
    
    /**
     * Return all tracks
     */
    public function index($method, $sub = null) {
        switch($method) {
            case 'survey':
                return $this->survey();
        }
    }

    /**
     * Get the survey
     * Requires private access
     * @return mixed[string] 
     */
    public function survey() {
        if (!\ClubSpeed\Security\Validate::privateAccess()) {
            throw new RestException(401, "Invalid authorization!");
        }

        $tsql = "select id, ss.custId as customerId, c.fname as firstName, c.lname as lastName, c.BirthDate as birthDate, c.EmailAddress as email, purchasePreference, ownsSubaru, l.locationname as location, createdAt from Subaru_Survey ss LEFT JOIN locations l on l.locationid = ss.locationId left join customers c on c.custid = ss.custId";
        $rows = $this->run_query($tsql, array());
        return array('responses' => $rows); 
    }
    
    private function run_query($tsql, $params = array()) {
        
        // Connect
        try {
            $conn = new PDO( "sqlsrv:server=(local) ; Database=ClubSpeedV8", "", "");
            $conn->setAttribute( PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION );
            
            // Prepare statement
            $stmt = $conn->prepare($tsql);
    
            // Execute statement
            $stmt->execute($params);
            
            // Put in array
            $output = $stmt->fetchAll(PDO::FETCH_ASSOC);

        } catch(Exception $e) { 
            die( print_r( $e->getMessage() ) ); 
        }
        
        return $output;
    }
    
}